import { startAmbient, stopAmbient } from './ambient.js';
import { revealCards, revealView, warmMotion } from './motion.js';

const worker = new Worker(new URL('../workers/fast-parse-worker.js', import.meta.url), { type: 'module' });
const $ = id => document.getElementById(id);
const nf = new Intl.NumberFormat(undefined, { maximumFractionDigits: 0 });
const df = new Intl.NumberFormat(undefined, { maximumFractionDigits: 1 });
const el = {
  ambient:$('ambient-root'), empty:$('empty-state'), parse:$('parse-state'), workspace:$('workspace'), file:$('file-input'), open:$('open-file'), replace:$('replace-file'), drop:$('drop-zone'), overlay:$('drop-overlay'), cancel:$('cancel-parse'), status:$('topbar-status'), nav:$('app-nav'), root:$('view-root'), player:$('player-select'), title:$('workspace-title'), eye:$('file-eyebrow'), toast:$('toast-region'), bar:$('progress-bar'), read:$('parse-read'), lines:$('parse-lines'), parsed:$('parse-parsed'), rejected:$('parse-rejected'), elapsed:$('parse-elapsed'), fileName:$('parse-file-name'), phase:$('parse-phase'), partial:$('partial-list')
};
const state = { view:'overview', summary:null, playerRef:'', report:null, reportRef:'', rawRows:[], rawNext:0, rawLoading:false };
let seq = 0;
const pending = new Map();
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = v => nf.format(Number(v)||0);
const compact = v => { const n=Number(v)||0; return Math.abs(n)>=1e9?`${df.format(n/1e9)}B`:Math.abs(n)>=1e6?`${df.format(n/1e6)}M`:Math.abs(n)>=1e3?`${df.format(n/1e3)}K`:num(n); };
const pct = v => `${df.format(Number(v)||0)}%`;
const bytes = v => { const n=Number(v)||0; return n>=1073741824?`${df.format(n/1073741824)} GB`:n>=1048576?`${df.format(n/1048576)} MB`:n>=1024?`${df.format(n/1024)} KB`:`${num(n)} B`; };
const dur = v => { const n=Math.max(0,Number(v)||0),m=Math.floor(n/60),s=Math.floor(n%60); return m?`${m}m ${String(s).padStart(2,'0')}s`:`${df.format(n)}s`; };
function toast(text,tone='info'){ el.toast.innerHTML=`<div class="toast ${tone}">${esc(text)}</div>`; clearTimeout(toast.t); toast.t=setTimeout(()=>el.toast.innerHTML='',4000); }
function status(text,tone='idle'){ el.status.dataset.tone=tone; el.status.innerHTML=`<span class="status-dot"></span><span>${esc(text)}</span>`; }
function mode(name){ el.empty.hidden=name!=='empty'; el.parse.hidden=name!=='parsing'; el.workspace.hidden=name!=='workspace'; name==='empty'?startAmbient(el.ambient):stopAmbient(); }
function setView(view){ state.view=view; el.nav.querySelectorAll('[data-view]').forEach(b=>{const on=b.dataset.view===view;b.classList.toggle('is-active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}); el.title.textContent=({overview:'Combat overview',players:'Party performance',powers:'Power analysis',events:'Event explorer',diagnostics:'Parser diagnostics'})[view]; }
function request(type,payload={}){ const requestId=++seq; return new Promise((resolve,reject)=>{ pending.set(requestId,{resolve,reject}); worker.postMessage({type,requestId,...payload}); setTimeout(()=>{if(pending.has(requestId)){pending.delete(requestId);reject(new Error(`${type} timed out`));}},30000); }); }
function settle(m){ const p=pending.get(m.requestId); if(!p)return false; pending.delete(m.requestId); if(m.error)p.reject(new Error(m.error)); else if('report' in m)p.resolve(m.report); else if('page' in m)p.resolve(m.page); else if('summary' in m)p.resolve(m.summary); else p.resolve(m); return true; }
function enableNav(on){ el.nav.querySelectorAll('[data-view]').forEach(b=>b.disabled=!on&&b.dataset.view!=='overview'); }
function fillPlayers(){ const list=state.summary?.players||[]; el.player.innerHTML=list.map(p=>`<option value="${esc(p.ref)}" ${p.ref===state.playerRef?'selected':''}>${esc(p.name)}</option>`).join(''); }
function metric(label,value,note=''){ return `<article class="metric-card" data-motion-card><span>${esc(label)}</span><strong>${value}</strong>${note?`<small>${esc(note)}</small>`:''}</article>`; }
function coverage(s){ const total=s.parsed+s.rejected, v=total?s.parsed/total*100:0; return `<span class="coverage ${s.rejected?'warn':'good'}"><i></i>${v.toFixed(2)}% accepted</span>`; }
function playerTable(players,short=false){ if(!players.length)return'<div class="empty-block">No players detected.</div>'; const max=Math.max(1,...players.map(p=>p.damage)); return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Player</th><th>Damage</th><th>DPS</th><th>Combat DPS</th>${short?'':'<th>Crit</th><th>Flank</th><th>Companion</th><th>Taken</th>'}</tr></thead><tbody>${players.map((p,i)=>`<tr data-player-row="${esc(p.ref)}" class="${p.ref===state.playerRef?'selected':''}"><td>${i+1}</td><td><strong>${esc(p.name)}</strong><span class="mini-bar"><i style="--bar:${p.damage/max*100}%"></i></span></td><td>${num(p.damage)}</td><td>${num(p.dps)}</td><td class="accent">${num(p.combatDps)}</td>${short?'':`<td>${pct(p.crit)}</td><td>${pct(p.flank)}</td><td>${num(p.companionDamage)}</td><td>${num(p.damageTaken)}</td>`}</tr>`).join('')}</tbody></table></div>`; }
function bindRows(){ el.root.querySelectorAll('[data-player-row]').forEach(row=>row.addEventListener('click',()=>selectPlayer(row.dataset.playerRow))); }
function selectPlayer(ref){ state.playerRef=ref; state.report=null; state.reportRef=''; state.rawRows=[]; state.rawNext=0; el.player.value=ref; if(state.view==='overview')state.view='powers'; render(); }
function renderOverview(){ const s=state.summary; el.root.innerHTML=`<section class="metrics">${metric('Parsed events',num(s.parsed),`${num(s.rejected)} rejected`)}${metric('Outgoing damage',compact(s.damage),`${num(s.validDamageRows)} valid hits`)}${metric('Combat duration',dur(s.duration),`${s.encounters.length} windows`)}${metric('Worker memory',bytes(s.estimatedStoreBytes),`${num(s.storedRows)} compact rows`)}</section><section class="panel"><div class="panel-head"><div><span class="eyebrow">Party ranking</span><h2>Damage contribution</h2></div>${coverage(s)}</div>${playerTable(s.players.slice(0,20),true)}</section><section class="panel"><div class="panel-head"><div><span class="eyebrow">Encounters</span><h2>Detected combat windows</h2></div><span>${s.encounters.length}</span></div><div class="encounters">${s.encounters.slice(0,24).map(e=>`<article class="encounter ${e.type==='boss'?'boss':''}"><span>${e.type==='boss'?'Boss':'Combat'} ${e.id}</span><strong>${esc(e.label)}</strong><small>${dur(e.duration)} · ${compact(e.damage)} dmg</small></article>`).join('')}</div></section>`; bindRows(); revealCards(el.root); }
function renderPlayers(){ el.root.innerHTML=`<section class="panel"><div class="panel-head"><div><span class="eyebrow">Party</span><h2>Player performance</h2></div><span>${state.summary.players.length} players</span></div>${playerTable(state.summary.players)}</section>`; bindRows(); }
async function report(){ if(!state.playerRef)return null; if(state.report&&state.reportRef===state.playerRef)return state.report; const ref=state.playerRef,r=await request('player-report',{playerRef:ref}); if(ref!==state.playerRef)return null; state.report=r;state.reportRef=ref;return r; }
function timeline(points){ if(!points?.length)return'<div class="empty-block">No timeline data.</div>'; const w=900,h=190,p=18,max=Math.max(1,...points.map(x=>x.damage)),end=Math.max(1,points.at(-1).second); const d=points.map((x,i)=>`${i?'L':'M'}${p+x.second/end*(w-p*2)},${h-p-x.damage/max*(h-p*2)}`).join(' '); return `<svg class="timeline" viewBox="0 0 ${w} ${h}" role="img" aria-label="Damage timeline"><path d="${d}"/></svg>`; }
async function renderPowers(){ el.root.innerHTML='<div class="empty-block">Building player report...</div>'; const r=await report(); if(!r)return; el.root.innerHTML=`<section class="metrics">${metric('Damage',compact(r.damage))}${metric('Combat DPS',num(r.combatDps))}${metric('Critical',pct(r.crit))}${metric('Flank / CA',pct(r.flank))}</section><section class="panel"><div class="panel-head"><div><span class="eyebrow">${esc(r.name)}</span><h2>Damage timeline</h2></div><span>${num(r.hits)} hits</span></div>${timeline(r.timeline)}</section><section class="panel"><div class="panel-head"><div><span class="eyebrow">Power breakdown</span><h2>Where damage came from</h2></div><span>${r.powers.length} powers</span></div><div class="table-wrap"><table><thead><tr><th>Power</th><th>Damage</th><th>Share</th><th>Hits</th><th>Avg</th><th>Max</th><th>Crit</th></tr></thead><tbody>${r.powers.map(p=>`<tr><td><strong>${esc(p.power)}</strong></td><td>${num(p.damage)}</td><td>${pct(p.share)}</td><td>${num(p.hits)}</td><td>${num(p.avg)}</td><td>${num(p.max)}</td><td>${pct(p.crit)}</td></tr>`).join('')}</tbody></table></div></section>`; revealCards(el.root); }
async function loadRaw(reset=false){ if(state.rawLoading)return;state.rawLoading=true;if(reset){state.rawRows=[];state.rawNext=0;}try{const page=await request('raw-page',{options:{cursor:state.rawNext||0,limit:180,playerRef:state.playerRef}});state.rawRows.push(...page.rows);state.rawNext=page.nextCursor;renderEvents(false);}catch(e){toast(e.message,'bad');}finally{state.rawLoading=false;} }
function renderEvents(auto=true){ el.root.innerHTML=`<section class="panel"><div class="panel-head"><div><span class="eyebrow">Paged worker query</span><h2>Raw event explorer</h2></div><span>${num(state.rawRows.length)} shown</span></div>${state.rawRows.length?`<div class="table-wrap raw"><table><thead><tr><th>Time</th><th>Owner</th><th>Target</th><th>Power</th><th>Type</th><th>Amount</th></tr></thead><tbody>${state.rawRows.map(r=>`<tr><td>${r.time.toFixed(2)}s</td><td>${esc(r.ownerName)}</td><td>${esc(r.targetName)}</td><td>${esc(r.powerName)}</td><td>${esc(r.damageType)}</td><td>${num(r.amount)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-block">Querying compact row store...</div>'}${state.rawNext!=null?'<button class="button load-more">Load 180 more</button>':''}</section>`; el.root.querySelector('.load-more')?.addEventListener('click',()=>loadRaw(false)); if(auto&&!state.rawRows.length)loadRaw(true); }
function renderDiagnostics(){ const s=state.summary; const list=(items,empty)=>items?.length?items.map(x=>`<div class="reason"><strong>${esc(x.key)}</strong><span>${num(x.value)}</span></div>`).join(''):`<div class="empty-block good-text">${empty}</div>`; el.root.innerHTML=`<section class="metrics">${metric('Accepted',num(s.parsed))}${metric('Rejected',num(s.rejected))}${metric('Valid damage',num(s.validDamageRows))}${metric('Stored rows',num(s.storedRows))}</section><section class="diagnostic-grid"><article class="panel"><div class="panel-head"><h2>Reject reasons</h2></div>${list(s.rejectReasons,'No rejected rows.')}</article><article class="panel"><div class="panel-head"><h2>Unknown event types</h2></div>${list(s.unknownTypes,'No unknown event types.')}</article></section><section class="panel"><div class="panel-head"><h2>Rejected row samples</h2><span>Max 40</span></div>${s.rejectedSamples?.length?`<div class="samples">${s.rejectedSamples.map(x=>`<article><b>Line ${num(x.lineNo)} · ${esc(x.reason)}</b><code>${esc(x.preview)}</code></article>`).join('')}</div>`:'<div class="empty-block good-text">Every structured row was accepted.</div>'}</section>`; }
async function render(){ setView(state.view); if(state.view==='overview')renderOverview(); else if(state.view==='players')renderPlayers(); else if(state.view==='powers')await renderPowers(); else if(state.view==='events')renderEvents(); else renderDiagnostics(); revealView(el.root); }
function finish(s){ state.summary=s;state.playerRef=s.players?.[0]?.ref||'';fillPlayers();enableNav(true);mode('workspace');status(`${num(s.parsed)} events ready`,s.rejected?'warn':'good');render();toast(`Parsed ${num(s.parsed)} events in ${(s.parseMs/1000).toFixed(2)}s`,'good'); }
function acceptFile(file){ if(!file)return;state.summary=null;state.report=null;state.rawRows=[];state.rawNext=0;mode('parsing');enableNav(false);el.fileName.textContent=file.name;el.eye.textContent=`${file.name} · ${bytes(file.size)}`;el.partial.innerHTML='<span class="empty-inline">Top players appear while parsing continues.</span>';el.bar.style.transform='scaleX(0)';status('Parsing worker active','working');worker.postMessage({type:'parse',file}); }
worker.onmessage=e=>{const m=e.data||{};if(m.requestId&&settle(m))return;if(m.type==='progress'){const p=m.progress,total=p.totalBytes||0,ratio=total?Math.min(1,p.bytesRead/total):0;el.bar.style.transform=`scaleX(${ratio})`;el.read.textContent=total?`${bytes(p.bytesRead)} / ${bytes(total)}`:bytes(p.bytesRead);el.lines.textContent=num(p.lineNo);el.parsed.textContent=num(p.parsed);el.rejected.textContent=num(p.rejected);el.elapsed.textContent=`${(p.elapsedMs/1000).toFixed(1)}s`;el.phase.textContent=p.phase==='finalizing'?'Building final indexes...':'Streaming and indexing...';status(`${Math.round(ratio*100)}% parsed`,'working');}else if(m.type==='partial-summary'){const ps=(m.summary.players||[]).slice(0,6),max=Math.max(1,...ps.map(p=>p.damage));el.partial.innerHTML=ps.map((p,i)=>`<div class="partial-row"><span>${i+1}</span><strong>${esc(p.name)}</strong><i style="--bar:${Math.max(2,p.damage/max*100)}%"></i><b>${compact(p.damage)}</b></div>`).join('');}else if(m.type==='done')finish(m.summary);else if(m.type==='error'){mode('empty');status('Parser error','bad');toast(m.message||'Parser failed','bad');}};
worker.onerror=e=>{mode('empty');status('Worker crashed','bad');toast(e.message||'Worker crashed','bad');};
el.open.addEventListener('click',()=>el.file.click());el.replace.addEventListener('click',()=>el.file.click());el.drop.addEventListener('click',()=>el.file.click());el.file.addEventListener('change',()=>{acceptFile(el.file.files?.[0]);el.file.value='';});el.cancel.addEventListener('click',()=>{worker.postMessage({type:'cancel'});mode('empty');status('Parse cancelled');});el.player.addEventListener('change',()=>selectPlayer(el.player.value));el.nav.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b||b.disabled)return;state.view=b.dataset.view;if(state.view==='events'){state.rawRows=[];state.rawNext=0;}render();});
let drag=0;addEventListener('dragenter',e=>{if(!e.dataTransfer?.types?.includes('Files'))return;e.preventDefault();drag++;el.overlay.hidden=false;});addEventListener('dragover',e=>{if(e.dataTransfer?.types?.includes('Files'))e.preventDefault();});addEventListener('dragleave',()=>{drag=Math.max(0,drag-1);if(!drag)el.overlay.hidden=true;});addEventListener('drop',e=>{e.preventDefault();drag=0;el.overlay.hidden=true;acceptFile(e.dataTransfer?.files?.[0]);});addEventListener('beforeunload',()=>worker.postMessage({type:'dispose'}));
mode('empty');enableNav(false);warmMotion();
