const state={rows:[],players:[],encounters:[],playerId:'',encounterId:'all',tab:'overview',showHidden:false,split:'player'};
const $=q=>document.querySelector(q);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(v,d=1){v=+v||0;const a=Math.abs(v);if(a>=1e9)return(v/1e9).toFixed(d)+'B';if(a>=1e6)return(v/1e6).toFixed(d)+'M';if(a>=1e3)return(v/1e3).toFixed(d)+'K';return Math.round(v).toLocaleString()}
function pct(v){return(+v||0).toFixed(1)+'%'}
function dur(s){s=Math.floor(+s||0);return Math.floor(s/60)+'m '+s%60+'s'}
function card(k,v){return`<div class="card"><b>${v}</b><span>${esc(k)}</span></div>`}
function table(rows,cols){return`<div class="table"><table><thead><tr>${cols.map(c=>`<th>${esc(c[1])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${formatCell(r[c[0]],c[0])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}">No rows</td></tr>`}</tbody></table></div>`}
function formatCell(v,k){if(v==null)return'-';if(['damage','total','avg','max','done','received','taken','shielded'].includes(k))return fmt(v);if(['share','crit','flank'].includes(k))return pct(v);if(['hits'].includes(k))return Math.round(v).toLocaleString();return esc(v)}
function currentRows(){if(state.encounterId==='all')return state.rows;const e=state.encounters.find(x=>String(x.id)===String(state.encounterId));return e?state.rows.filter(r=>r.time>=e.start&&r.time<=e.end):state.rows}
function currentEncounters(){return state.encounterId==='all'?state.encounters:state.encounters.filter(e=>String(e.id)===String(state.encounterId))}
function rebuildEncounters(){state.encounters=NWParser.buildEncounters(state.rows,state.playerId,state.split)}
function renderPlayers(){const sel=$('#player');sel.innerHTML=state.players.map(p=>`<option value="${esc(p.id)}" ${p.id===state.playerId?'selected':''}>${esc(p.name)}</option>`).join('');if(!state.players.length){$('#party').innerHTML='';return}const rows=state.players.map((p,i)=>{const m=NWParser.metrics(state.rows,p.id,state.encounters);return{rank:i+1,name:p.name,damage:m.total,dps:m.dps,combat:m.combatDps,hits:m.hits,duration:dur(m.duration)}});$('#party').innerHTML=`<section class="panel"><h3>Party Overview</h3>${table(rows,[['rank','#'],['name','Player'],['damage','Damage'],['dps','DPS'],['combat','Combat DPS'],['hits','Hits'],['duration','Duration']])}</section>`}
function renderChips(){if(!state.encounters.length){$('#chips').innerHTML='';return}const visible=state.showHidden?state.encounters:state.encounters.filter(e=>e.visible);const hidden=state.encounters.length-state.encounters.filter(e=>e.visible).length;$('#chips').innerHTML=`<button class="chip ${state.encounterId==='all'?'active':''}" data-e="all">All Encounters</button>`+visible.map(e=>`<button class="chip ${e.type} ${String(e.id)===String(state.encounterId)?'active':''}" data-e="${e.id}">${e.type==='boss'?'Boss':'Mob'} #${e.id} ${esc(e.label)} ${dur(e.duration)}</button>`).join('')+(hidden?`<button id="hidden" class="chip ghost">${state.showHidden?'Hide':'Show'} ${hidden} hidden / non-boss</button>`:'');document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{state.encounterId=b.dataset.e;render()});const h=$('#hidden');if(h)h.onclick=()=>{state.showHidden=!state.showHidden;render()}}
function renderOverview(rows,pid,encs){const m=NWParser.metrics(rows,pid,encs);const h=NWParser.healing(rows,pid);const powers=NWParser.powers(rows,pid).slice(0,8);const max=m.max;$('#content').innerHTML=`<section class="panel"><h3>Overview</h3><div class="cards">${card('Total Damage',fmt(m.total))}${card('DPS',fmt(m.dps))}${card('Combat DPS',fmt(m.combatDps))}${card('Duration',dur(m.duration))}${card('In-Combat Time',dur(m.combatTime))}${card('Hits',Math.round(m.hits).toLocaleString())}${card('Crit Rate',pct(m.crit))}${card('Flank Rate',pct(m.flank))}${card('Max Hit '+(max?'('+esc(max.powerName)+')':''),fmt(max?.amount||0))}${card('Encounters',encs.length)}${card('Healing Done',fmt(h.done))}${card('Damage Taken',fmt(NWParser.taken(rows,pid)))}${card('Shielded',fmt(NWParser.shielded(rows,pid)))}</div><h3>Top Damage Powers</h3>${table(powers,[['power','Power'],['category','Category'],['hits','Hits'],['damage','Damage'],['share','%'],['avg','Avg'],['max','Max'],['crit','Crit%']])}</section>`}
function renderDamage(rows,pid){const powers=NWParser.powers(rows,pid);$('#content').innerHTML=`<section class="panel"><h3>Damage Out</h3>${table(powers,[['power','Power'],['category','Category'],['hits','Hits'],['damage','Damage'],['share','%'],['avg','Avg'],['max','Max'],['crit','Crit%']])}<div id="raw"></div></section>`;document.querySelectorAll('#content tbody tr').forEach((tr,i)=>tr.onclick=()=>renderRaw(powers[i]))}
function renderRaw(power){if(!power)return;const first=power.rows[0]?.time||0;const rows=power.rows.map(r=>({time:r.timestampRaw,offset:'+'+(r.time-first).toFixed(2)+'s',target:r.targetName,damage:r.amount,base:r.baseAmount,debuff:r.baseAmount?((r.amount/r.baseAmount-1)*100).toFixed(0)+'%':'-',type:r.damageType,flags:[r.flags.has('Critical')?'CRIT':'',r.flags.has('Flank')?'CA':'',r.flags.has('Dodge')?'DEFLECT':''].filter(Boolean).join(' ')}));$('#raw').innerHTML=`<div class="raw"><h3>Raw hits - ${esc(power.power)} (${power.rows.length})</h3>${table(rows,[['time','Time'],['offset','Offset'],['target','Target'],['damage','Damage'],['base','Base'],['debuff','Debuff%'],['type','Type'],['flags','Flags']])}</div>`}
function renderSimple(rows,pid,type){const h=NWParser.healing(rows,pid);if(type==='healing'){$('#content').innerHTML=`<section class="panel"><h3>Healing</h3><div class="cards">${card('Healing Done',fmt(h.done))}${card('Healing Received',fmt(h.received))}</div></section>`;return}if(type==='taken'){$('#content').innerHTML=`<section class="panel"><h3>Damage Taken</h3><div class="cards">${card('Damage Taken',fmt(NWParser.taken(rows,pid)))}</div></section>`;return}if(type==='shield'){$('#content').innerHTML=`<section class="panel"><h3>Shielding</h3><div class="cards">${card('Shielded',fmt(NWParser.shielded(rows,pid)))}</div></section>`;return}}
function renderPosition(rows,pid){const dmg=NWParser.validForPlayer(rows,pid).filter(r=>!r.flags.has('Dodge'));const actual=dmg.reduce((s,r)=>s+r.amount,0);const ca=dmg.filter(r=>r.flags.has('Flank'));const non=dmg.filter(r=>!r.flags.has('Flank')).reduce((s,r)=>s+r.amount,0);const missed=non*(2.2-1);const potential=actual+missed;$('#content').innerHTML=`<section class="panel"><h3>Combat Advantage Positioning</h3><div class="cards">${card('CA Uptime',pct(dmg.length?ca.length/dmg.length*100:0))}${card('Positioning Efficiency',pct(potential?actual/potential*100:100))}${card('Actual Damage',fmt(actual))}${card('Potential Damage',fmt(potential))}${card('Missed CA Damage',fmt(missed))}</div></section>`}
function renderTiming(rows,pid){const damage=NWParser.validForPlayer(rows,pid).filter(r=>r.baseAmount>0&&['Daily','Mount'].includes(NWParser.category(r.powerName)));let actual=0,potential=0;for(const r of damage){const cur=r.amount/r.baseAmount;let best=cur;for(const x of NWParser.validForPlayer(rows,pid).filter(x=>x.targetId===r.targetId&&x.baseAmount>0&&Math.abs(x.time-r.time)<=15)){best=Math.max(best,x.amount/x.baseAmount)}actual+=r.amount;potential+=r.amount/cur*best}$('#content').innerHTML=`<section class="panel"><h3>Timing Analysis</h3><p class="mut">Compares current damage/base multiplier to the best same-target window within ±15 seconds. Enemy debuff timing only.</p><div class="cards">${card('Timing Efficiency',pct(potential?actual/potential*100:100))}${card('Actual Damage',fmt(actual))}${card('Potential Damage',fmt(potential))}${card('Missed Damage',fmt(potential-actual))}</div></section>`}
function renderFormulas(){$('#content').innerHTML=`<section class="panel"><h3>Combat Formulas</h3><p>Rating contribution = 50 + (Rating - TIL) / 1000.</p><p>Base Damage = (TIL / 10) × role multiplier.</p><p>Base HP = (TIL × 10) × role multiplier.</p><p>Actual theoretical damage = (Magnitude / 100) × Base Damage × Multipliers.</p><p>Parser damage = sum of final logged Physical damage rows.</p><p>Boss entity = template contains _Boss. Mob entity = template contains _Solo, _Elite, _Standard, or _Minion.</p><p>DPS = Total Damage / first-to-last damage duration. Combat DPS = Total Damage / active encounter time.</p></section>`}
function render(){renderPlayers();renderChips();document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));if(!state.playerId)return;const rows=currentRows();const encs=currentEncounters();if(state.tab==='overview')renderOverview(rows,state.playerId,encs);else if(state.tab==='damage')renderDamage(rows,state.playerId);else if(['healing','taken','shield'].includes(state.tab))renderSimple(rows,state.playerId,state.tab);else if(state.tab==='pos')renderPosition(rows,state.playerId);else if(state.tab==='timing')renderTiming(rows,state.playerId);else renderFormulas()}
async function load(file){$('#status').textContent='Reading '+file.name+'...';state.rows=NWParser.parseLog(await file.text());state.players=NWParser.detectPlayers(state.rows);state.playerId=state.players[0]?.id||'';state.encounterId='all';rebuildEncounters();$('#status').textContent='Parsed '+state.rows.length.toLocaleString()+' rows.';render()}
$('#file').onchange=e=>{if(e.target.files[0])load(e.target.files[0])};$('#player').onchange=e=>{state.playerId=e.target.value;state.encounterId='all';rebuildEncounters();render()};$('#mode').onchange=e=>{state.split=e.target.value;state.encounterId='all';rebuildEncounters();render()};$('#tabs').onclick=e=>{const b=e.target.closest('button');if(b?.dataset.tab){state.tab=b.dataset.tab;render()}};
