(function(){
  const ROOT='https://nw-hub.com/assets/';
  const DIR={classes:ROOT+'classes/',powers:ROOT+'powers/',mountPowers:ROOT+'mount-powers/',mounts:ROOT+'mounts/',artifacts:ROOT+'artifacts/',companions:ROOT+'companions/',enchantments:ROOT+'enchantments/',overloads:ROOT+'overloads/',buffs:ROOT+'buffs/',debuff:ROOT+'debuff/',mechanics:ROOT+'mechanics/'};
  const CLASS={Barbarian:DIR.classes+'icons/barbarian.webp',Bard:DIR.classes+'icons/bard.webp',Cleric:DIR.classes+'icons/cleric.webp',Fighter:DIR.classes+'icons/fighter.webp',Paladin:DIR.classes+'icons/paladin.webp',Ranger:DIR.classes+'icons/ranger.webp',Rogue:DIR.classes+'icons/rogue.webp',Warlock:DIR.classes+'icons/warlock.webp',Wizard:DIR.classes+'icons/wizard.webp'};
  const KNOWN='aimed-shot arcane-bolt arcane-conduit arcane-singularity arcane-tempest arms-of-hadar aura-of-courage aura-of-protection bane bastion-of-health blade-hurricane blade-storm blazing-flamenco block bloodbath bloodletter brash-strike burning-light careful-attack chain-of-blazing-light chill-strike chilling-cloud cleave cloud-of-steel combat-superiority commandingshot commanding-shot cordon-of-arrows crescendo cure-wounds dazing-strike deft-strike disheartening-strike disruptive-shot divine-glow divine-touch eldritch-blast electric-shot entangling-force fanning-the-flame fiery-bolt fireball forest-ghost forgemasters-flame frenzy gloaming-cut glowing-flames grasping-roots hand-of-blight hadars-grasp healing-word hindering-shot ice-knife icy-rays icy-terrain indomitable-rage infernal-sanction infernal-spheres killing-flames knee-breaker lance-of-faith lashing-blade lay-on-hands linebreaker longstriders-shot magic-missile marauders-escape mighty-leap path-of-the-blade pillar-of-power rain-of-arrows rapid-shot rapid-volley ray-of-enfeeblement ray-of-frost radiant-slam repel sacred-flame sacred-weapon savage-advance scorching-burst searing-javelin seismic-shot shadow-strike shield shield-throw shatter-strike sly-flourish-power smite smoke-bomb soul-pact soul-scorch soulstorm split-shot split-the-sky steel-blitz thorn-ward threatening-rush tide-of-iron twin-blade-storm vampiric-embrace valorous-strike warlocks-bargain warlocks-curse wicked-reminder'.split(' ');
  const ALIAS={'hindering-strike':'hindering-shot','thorn-strike':'thorn-ward','throw-caution':'careful-attack','tail-sting':'tailwind-mambo','radiant-weapon':'sacred-weapon','rimefire-smolder':'rimefire-weaving'};
  const norm=s=>String(s||'').toLowerCase().replace(/['’]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const slug=s=>norm(s).replace(/\s+/g,'-');
  function classUrl(name){return CLASS[name]||CLASS[Object.keys(CLASS).find(k=>norm(k)===norm(name))]||''}
  function bestPowerSlug(name){const q=slug(name);if(ALIAS[q])return ALIAS[q];if(KNOWN.includes(q))return q;const qt=q.split('-').filter(Boolean);let best='',score=0;for(const f of KNOWN){const ft=f.split('-');const hit=qt.filter(t=>ft.includes(t)).length;if(hit>score){score=hit;best=f}}return score?best:q}
  function powerUrl(name,cat){const s=bestPowerSlug(name);if(cat==='Mount')return DIR.mountPowers+slug(name)+'.webp';if(cat==='Artifact')return DIR.artifacts+s+'.webp';if(cat==='Pet / Companion')return DIR.companions+s+'.webp';if(cat==='Item / Enchant')return DIR.enchantments+s+'.webp';return DIR.powers+s+'.webp'}
  function icon(u,cls,label){return u?'<span class="assetIcon '+(cls||'')+'" title="'+String(label||'')+'" style="background-image:url('+u+');background-size:cover;background-position:center;background-repeat:no-repeat"></span>':'<span class="nwIcon '+(cls||'')+'">?</span>'}
  function html(kind,name,alt,cls,opt){const u=kind==='class'?classUrl(name):powerUrl(name,opt&&opt.category);return icon(u,cls,alt||name)}
  window.NWAssets={ROOT,DIR,CLASS,KNOWN,ALIAS,norm,slug,bestPowerSlug,classUrl,powerUrl,html,powerHtml:(name,cat,cls)=>html('power',name,name,cls||'powerIcon',{category:cat})};
})();
