(function(){
  if(typeof state==='undefined')return;
  if(state.includeCompanions===undefined)state.includeCompanions=true;
  const baseScopeRows=scopeRows;
  const baseRender=render;
  function isCompanion(r){const c=NWParser.category(r.powerName);const txt=(r.sourceName+' '+r.sourceId+' '+r.powerName).toLowerCase();return c==='Pet / Companion'||/companion|pet_|appointment|summon/.test(txt)}
  function encounterRows(){return baseScopeRows()}
  function rowsForPlayer(pid){const rows=encounterRows();return state.includeCompanions?rows:rows.filter(r=>!(r.ownerId===pid&&isCompanion(r)))}
  function titleScope(){return state.encounterId==='all'?'All encounters':'Focused encounter #'+state.encounterId}
  function ensureTabs(){const tabs=$('#tabs');if(!tabs)return;if(!tabs.querySelector('[data-tab="compare"]'))tabs.insertAdjacentHTML('beforeend','<button data-tab="compare">Compare Players</button><button data-tab="companions">Companions</button>')}
  function ensureControls(){const tb=$('.toolbar');if(!tb||$('#compToggle'))return;tb.insertAdjacentHTML('beforeend','<label class="toggle"><input id="compToggle" type="checkbox" '+(state.includeCompanions?'checked':'')+'> Include companion damage</label>');$('#compToggle').onchange=e=>{state.includeCompanions=e.target.checked;state.rawPower=null;render()}}
  function setActive(){ensureTabs();$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));const t=$('#compToggle');if(t)t.checked=state.includeCompanions}
  function cls(p){return window.NWMeta?NWMeta.classBadge(NWMeta.inferClassForPlayer(p.id,state.rows)):esc(inferClass(p.id))}
  function metricRows(){return state.players.map(p=>{const rows=rowsForPlayer(p.id);const m=NWParser.metrics(rows,p.id,activeEncounters());return{p,rows,m}}).sort((a,b)=>b.m.total-a.m.total)}
  playerHeader=function(){const p=player();if(!p)return'';const rows=rowsForPlayer(p.id);const m=NWParser.metrics(rows,p.id,activeEncounters());const tag=state.includeCompanions?'Companions Included':'Player Damage Only';return '<div class="playerHead pro"><div><div class="playerName">'+cls(p)+' <span>'+esc(p.name)+'</span> <span class="badge green">'+tag+'</span></div><small class="mut">'+titleScope()+'</small></div><div><span class="badge">'+fmt(m.total)+' damage</span><span class="badge">'+fmt(m.combatDps)+' combat DPS</span><span class="badge red">'+num(deathRows(encounterRows(),p.id).length)+' deaths</span></div></div>'};
  renderPlayers=function(){const sel=$('#player');sel.innerHTML=state.players.map(p=>'<option value="'+esc(p.id)+'" '+(p.id===state.playerId?'selected':'')+'>'+esc(p.name)+'</option>').join('');if(!state.players.length){$('#party').innerHTML='';return}const rows=metricRows();let body='';rows.forEach((x,i)=>{body+='<tr class="partyRow '+(x.p.id===state.playerId?'selected':'')+'" data-pi="'+state.players.indexOf(x.p)+'"><td>'+num(i+1)+'</td><td><b>'+esc(x.p.name)+'</b></td><td>'+cls(x.p)+'</td><td>'+fmt(x.m.total)+'</td><td>'+fmt(x.m.dps)+'</td><td>'+fmt(x.m.combatDps)+'</td><td>'+num(x.m.hits)+'</td><td>'+dur(x.m.duration)+'</td></tr>'});$('#party').innerHTML='<section class="panel partyPanel"><h3>Party Overview <span class="infoDot" title="Filtered by the selected boss or mob chip. Click a player row to inspect them below.">i</span></h3><div class="table"><table><thead><tr><th>#</th><th>Player</th><th>Class</th><th>Damage</th><th>DPS</th><th>Combat DPS</th><th>Hits</th><th>Duration</th></tr></thead><tbody>'+body+'</tbody></table></div></section>';$$('.partyRow').forEach(tr=>tr.onclick=()=>{const p=state.players[+tr.dataset.pi];if(p){state.playerId=p.id;state.rawPower=null;render()}})};
  scopeRows=function(){const p=player();return p?rowsForPlayer(p.id):encounterRows()};
  function renderCompare(){const rows=metricRows();const max=Math.max(1,...rows.map(x=>x.m.total));let body='';rows.forEach((x,i)=>{const pet=companionTotal(x.p.id);body+='<tr data-pi="'+state.players.indexOf(x.p)+'" class="partyRow"><td>'+num(i+1)+'</td><td><b>'+esc(x.p.name)+'</b></td><td>'+cls(x.p)+'</td><td>'+fmt(x.m.total)+'</td><td>'+fmt(x.m.combatDps)+'</td><td>'+pct(x.m.crit)+'</td><td>'+pct(x.m.flank)+'</td><td>'+fmt(pet)+'</td><td><div class="miniBar"><i style="width:'+Math.max(2,x.m.total/max*100)+'%"></i></div></td></tr>'});$('#content').innerHTML='<section class="panel"><h3>Compare Players <span class="infoDot" title="Uses the selected encounter filter and the companion damage toggle.">i</span></h3><p class="mut">Quickly see who carried damage, who relied on companion damage, and who had better combat-time output.</p><div class="table"><table><thead><tr><th>#</th><th>Player</th><th>Class</th><th>Damage</th><th>Combat DPS</th><th>Crit</th><th>Flank</th><th>Companion</th><th>Share</th></tr></thead><tbody>'+body+'</tbody></table></div></section>';$$('.partyRow').forEach(tr=>tr.onclick=()=>{const p=state.players[+tr.dataset.pi];if(p){state.playerId=p.id;state.tab='overview';render()}})}
  function companionTotal(pid){return encounterRows().filter(r=>r.ownerId===pid&&isCompanion(r)&&NWParser.isDamage(r)).reduce((s,r)=>s+r.amount,0)}
  function renderCompanions(){const rows=encounterRows().filter(r=>isCompanion(r)&&NWParser.isDamage(r));const total=rows.reduce((s,r)=>s+r.amount,0);const map=new Map();rows.forEach(r=>{const k=r.ownerId+'|'+r.ownerName+'|'+(r.sourceName||r.powerName)+'|'+r.powerName;if(!map.has(k))map.set(k,{ownerId:r.ownerId,player:r.ownerName,source:r.sourceName||'-',power:r.powerName,damage:0,hits:0});const x=map.get(k);x.damage+=r.amount;x.hits++});const list=Array.from(map.values()).sort((a,b)=>b.damage-a.damage);let body=list.map((x,i)=>'<tr data-owner="'+esc(x.ownerId)+'"><td>'+num(i+1)+'</td><td><b>'+esc(x.player)+'</b></td><td>'+esc(x.source)+'</td><td>'+esc(x.power)+'</td><td>'+fmt(x.damage)+'</td><td>'+pct(total?x.damage/total*100:0)+'</td><td>'+num(x.hits)+'</td></tr>').join('');$('#content').innerHTML='<section class="panel"><h3>Companion Damage Ranking <span class="infoDot" title="Ranks damage from powers or sources classified as companions or pets in the current encounter filter.">i</span></h3><p class="mut">Use this with the toggle above to see how much companion damage changes the player ranking.</p><div class="cards">'+card('Total Companion Damage',fmt(total))+card('Companion Rows',num(rows.length))+card('Contributors',num(new Set(list.map(x=>x.player)).size))+'</div><div class="table"><table><thead><tr><th>#</th><th>Player</th><th>Source</th><th>Power</th><th>Damage</th><th>Share</th><th>Hits</th></tr></thead><tbody>'+(body||'<tr><td colspan="7" class="empty">No companion damage found in this scope</td></tr>')+'</tbody></table></div></section>';$$('[data-owner]').forEach(tr=>tr.onclick=()=>{state.playerId=tr.dataset.owner;state.tab='overview';render()})}
  render=function(){ensureTabs();ensureControls();if(state.tab==='compare'){renderPlayers();renderChips();setActive();renderCompare();return}if(state.tab==='companions'){renderPlayers();renderChips();setActive();renderCompanions();return}baseRender();ensureTabs();ensureControls();setActive()};
  const st=document.createElement('style');st.textContent='.partyRow{cursor:pointer}.partyRow.selected td{background:rgba(70,215,183,.08)!important}.toggle{display:inline-flex;align-items:center;gap:6px}.infoDot{display:inline-grid;place-items:center;width:16px;height:16px;border-radius:50%;border:1px solid #52637a;color:#46d7b7;font-size:10px}.miniBar{height:10px;background:#0b121b;border-radius:999px;overflow:hidden}.miniBar i{display:block;height:100%;background:#46d7b7;border-radius:999px}';document.head.appendChild(st);
  render();
})();
