const CAT={"Chilling Cloud":"At-Will","Magic Missile":"At-Will","Electric Shot":"At-Will","Rapid Shot":"At-Will","Icy Rays":"Encounter","Chill Strike":"Encounter","Repel":"Encounter","Entangling Force":"Encounter","Fanning the Flame":"Encounter","Fanned Flame":"Encounter","Gathering Flame":"Encounter","Fireball":"Encounter","Icy Terrain":"Encounter","Thorn Ward":"Encounter","Thorn Strike":"Encounter","Hindering Strike":"Encounter","Split the Sky":"Encounter","Throw Caution":"Encounter","Hindering Shot":"Encounter","Ice Knife":"Daily","Furious Immolation":"Daily","Forest Ghost":"Daily","Infernal Pounce":"Mount","Rimefire Smolder":"Feat","Shatter Strike":"Feat","Glowing Flames":"Feat","Grasping Roots":"Feat","Smolder":"Class Feature","Mark of the Giant Slayer, Rank 2":"Item / Enchant","Empowered Owlbear Figurine":"Item / Enchant","Spined Devil's Influence":"Item / Enchant","Lightning Flash":"Item / Enchant","Enchanter's Hex":"Item / Enchant","Loose the Ballista!":"Pet / Companion","Suppressing Fire!":"Pet / Companion","Slash":"Pet / Companion","Thrust":"Pet / Companion","Instructional Aid":"Pet / Companion","Life Lessons":"Other / Unknown","Radiant Weapon":"Other / Unknown","Blood Lust":"Other / Unknown","Tentacle Slam":"Other / Unknown","Infection":"Other / Unknown"};
function csv(line){const out=[];let c='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){q=!q}else if(ch===','&&!q){out.push(c);c=''}else c+=ch}out.push(c);return out}
function sec(raw){const p=raw.split(':');return p.length<6?0:(+p[2])*86400+(+p[3])*3600+(+p[4])*60+(+p[5])}
function parseEntity(id=''){const m=String(id).match(/^C\[(\d+)\s+(.+)\]$/);return m?{num:m[1],tpl:m[2]}:null}
function isPlayer(id){return String(id).startsWith('P[')}
function isCreature(id){return String(id).startsWith('C[')}
function isBoss(id){return (parseEntity(id)?.tpl||'').includes('_Boss')}
function isMob(id){const t=parseEntity(id)?.tpl||'';return !t.includes('_Boss')&&['_Solo','_Elite','_Standard','_Minion'].some(x=>t.includes(x))}
function isDamage(r){return r.damageType==='Physical'&&r.amount>0&&!r.flags.has('ShowPowerDisplayName')&&(r.targetId!=='*'||isCreature(r.sourceId))}
function parseLog(text){const rows=[];for(const line of text.split(/\r?\n/)){if(!line||line.startsWith('index,'))continue;const c=csv(line.trim());if(c.length<12)continue;const k=c[0].indexOf('::');if(k<0)continue;const ts=c[0].slice(0,k);const amount=+c[10];if(!Number.isFinite(amount))continue;rows.push({timestampRaw:ts,abs:sec(ts),time:0,ownerName:c[0].slice(k+2),ownerId:c[1]||'',sourceName:c[2]||'',sourceId:c[3]||'',targetName:c[4]||'',targetId:c[5]||'',powerName:c[6]||'Unknown',powerId:c[7]||'',damageType:c[8]||'',flags:new Set((c[9]||'').split('|').filter(Boolean)),flagsRaw:c[9]||'',amount,baseAmount:+c[11]||0})}const first=Math.min(...rows.map(r=>r.abs));rows.forEach(r=>r.time=Math.round((r.abs-first)*1000)/1000);return rows}
function detectPlayers(rows){const m=new Map();for(const r of rows){if(isPlayer(r.ownerId)){if(!m.has(r.ownerId))m.set(r.ownerId,{id:r.ownerId,name:r.ownerName,damage:0,hits:0});if(isDamage(r)){const p=m.get(r.ownerId);p.damage+=r.amount;p.hits++}}}return [...m.values()].sort((a,b)=>b.damage-a.damage)}
function validForPlayer(rows,pid){return rows.filter(r=>r.ownerId===pid&&isDamage(r))}
function enemyStats(rows){const m=new Map();for(const r of rows){if(!isCreature(r.targetId))continue;if(!m.has(r.targetId)){const e=parseEntity(r.targetId);m.set(r.targetId,{id:r.targetId,name:r.targetName||e?.tpl||r.targetId,tpl:e?.tpl||'',damage:0,hits:0,boss:isBoss(r.targetId),mob:isMob(r.targetId),first:r.time})}const x=m.get(r.targetId);x.damage+=Math.max(0,r.amount);x.hits+=r.amount>0?1:0;x.first=Math.min(x.first,r.time)}return [...m.values()].sort((a,b)=>a.boss!==b.boss?+b.boss-+a.boss:b.damage-a.damage||a.first-b.first)}
function makeEncounter(rs){const es=enemyStats(rs);const type=es.some(e=>e.boss)?'boss':'mob';const names=es.slice(0,3).map(e=>e.name);let label=names.join(', ')||'Trash';if(es.length>3)label+=' +'+(es.length-3);if(type!=='boss'&&es.length<=4)label='Trash ('+es.length+' mobs)';return{rows:rs,start:rs[0].time,end:rs.at(-1).time,type,label,visible:type==='boss',bossIds:new Set(es.filter(e=>e.boss).map(e=>e.id)),enemyStats:es}}
function sameBoss(a,b){for(const id of a.bossIds)if(b.bossIds.has(id))return true;return false}
function buildEncounters(rows,pid,mode='player'){const src=(mode==='party'?rows.filter(r=>isPlayer(r.ownerId)&&isDamage(r)):validForPlayer(rows,pid)).sort((a,b)=>a.time-b.time);const raw=[];let cur=[];for(const r of src){if(cur.length&&r.time-cur.at(-1).time>5){raw.push(makeEncounter(cur));cur=[]}cur.push(r)}if(cur.length)raw.push(makeEncounter(cur));const out=[];for(const e of raw){const p=out.at(-1);if(p&&p.type==='boss'&&e.type==='boss'&&sameBoss(p,e)&&e.start-p.end<=15)out[out.length-1]=makeEncounter([...p.rows,...e.rows]);else out.push(e)}return out.map((e,i)=>({...e,id:i+1,duration:e.end-e.start}))}
function category(power){return CAT[power]||'Other / Unknown'}
function group(rows,fn){const m=new Map();for(const r of rows){const k=fn(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return m}
function metrics(rows,pid,encounters=[]){const d=validForPlayer(rows,pid);const total=d.reduce((s,r)=>s+r.amount,0);const hits=d.length;const first=hits?d[0].time:0;const last=hits?d.at(-1).time:0;let combat=0;for(const e of encounters){const x=d.filter(r=>r.time>=e.start&&r.time<=e.end);if(x.length)combat+=x.at(-1).time-x[0].time}return{total,hits,duration:last-first,dps:total/Math.max(1,last-first),combatTime:combat,combatDps:total/Math.max(1,combat),crit:hits?d.filter(r=>r.flags.has('Critical')).length/hits*100:0,flank:hits?d.filter(r=>r.flags.has('Flank')).length/hits*100:0,max:d.reduce((b,r)=>r.amount>(b?.amount||0)?r:b,null)}}
function powers(rows,pid){const d=validForPlayer(rows,pid);const total=d.reduce((s,r)=>s+r.amount,0);return[...group(d,r=>r.powerName)].map(([power,rs])=>{const damage=rs.reduce((s,r)=>s+r.amount,0);return{power,category:category(power),hits:rs.length,damage,share:total?damage/total*100:0,avg:damage/rs.length,max:Math.max(...rs.map(r=>r.amount)),crit:rs.filter(r=>r.flags.has('Critical')).length/rs.length*100,rows:rs}}).sort((a,b)=>b.damage-a.damage)}
function healing(rows,pid){const out=rows.filter(r=>r.ownerId===pid&&r.damageType==='HitPoints'&&r.amount<0);const inc=rows.filter(r=>r.targetId===pid&&r.damageType==='HitPoints'&&r.amount<0);return{done:out.reduce((s,r)=>s+Math.abs(r.amount),0),received:inc.reduce((s,r)=>s+Math.abs(r.amount),0)}}
function taken(rows,pid){return rows.filter(r=>r.targetId===pid&&r.damageType==='Physical'&&r.amount>0).reduce((s,r)=>s+r.amount,0)}
function shielded(rows,pid){return rows.filter(r=>r.targetId===pid&&r.damageType==='Shield'&&r.amount<0).reduce((s,r)=>s+Math.abs(r.amount),0)}
window.NWParser={parseLog,detectPlayers,buildEncounters,metrics,powers,healing,taken,shielded,isDamage,validForPlayer,category};
