const state={rows:[],players:[],encounters:[],playerId:'',encounterId:'all',tab:'overview',showHidden:false,split:'player',rawPower:null,filter:'all',ca:2.2,includeEnc:false};
const $=q=>document.querySelector(q);
const $$=q=>Array.from(document.querySelectorAll(q));
const CD={"Entangling Force":16,"Fanning the Flame":22,"Fireball":12,"Icy Terrain":19,"Repel":11,"Icy Rays":18,"Chill Strike":15,"Thorn Ward":16,"Thorn Strike":12,"Hindering Strike":12,"Split the Sky":18,"Throw Caution":18,"Hindering Shot":12};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(v,d=1){v=+v||0;const a=Math.abs(v);if(a>=1e9)return(v/1e9).toFixed(d)+'B';if(a>=1e6)return(v/1e6).toFixed(d)+'M';if(a>=1e3)return(v/1e3).toFixed(d)+'K';return Math.round(v).toLocaleString()}
function num(v){return Math.round(+v||0).toLocaleString()}
function pct(v){return(+v||0).toFixed(1)+'%'}
function dur(s){s=Math.floor(+s||0);return Math.floor(s/60)+'m '+(s%60)+'s'}
function group(rows,fn){const m=new Map();for(const r of rows){const k=fn(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return m}
function sum(rows,fn){return rows.reduce((s,r)=>s+fn(r),0)}
function card(k,v){return`<div class="card"><b>${v}</b><span>${esc(k)}</span></div>`}
function cell(v,k){if(v==null)return'-';if(['damage','total','avg','max','done','received','taken','shielded','absorbed','nonca','missed','potential','actual','base'].includes(k))return fmt(v);if(['share','crit','critRate','flank','caRate','eff','uptime','effect'].includes(k))return pct(v);if(['hits','ticks','caHits','full','breaks','rank'].includes(k))return num(v);if(k==='time')return(+v).toFixed(1)+'s';if(k==='offset')return Math.abs(+v).toFixed(0)+'s '+(+v<0?'early':'late');if(k==='mult'||k==='best')return'x'+(+v).toFixed(2);return esc(v)}
function table(rows,cols){return`<div class="table"><table><thead><tr>${cols.map(c=>`<th>${esc(c[1])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${cell(r[c[0]],c[0])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}" class="empty">No rows</td></tr>`}</tbody></table></div>`}
function scopeRows(){if(state.encounterId==='all')return state.rows;const e=state.encounters.find(x=>String(x.id)===String(state.encounterId));return e?state.rows.filter(r=>r.time>=e.start&&r.time<=e.end):state.rows}
function activeEncounters(){return state.encounterId==='all'?state.encounters:state.encounters.filter(e=>String(e.id)===String(state.encounterId))}
function player(){return state.players.find(p=>p.id===state.playerId)||state.players[0]}
function inferClass(pid){const pows=new Set(NWParser.powers(state.rows,pid).map(p=>p.power));const hints=[['Wizard',['Chilling Cloud','Icy Rays','Repel','Entangling Force','Ice Knife','Furious Immolation']],['Ranger',['Electric Shot','Thorn Ward','Thorn Strike','Hindering Strike','Split the Sky','Forest Ghost']],['Warlock',['Vampiric Embrace','Pillar of Power','Soulstorm']],['Fighter',['Linebreaker','Shield Throw','Tendon Strike']]];let best=['Unknown',0];for(const h of hints){const s=h[1].filter(x=>pows.has(x)).length;if(s>best[1])best=[h[0],s]}return best[0]}
function rebuildEncounters(){state.encounters=NWParser.buildEncounters(state.rows,state.playerId,state.split)}
function playerHeader(){const p=player();if(!p)return'';const m=NWParser.metrics(scopeRows(),p.id,activeEncounters());return`<div class="playerHead"><div><div class="playerName">${esc(p.name)} <span class="badge">${inferClass(p.id)}</span> <span class="badge green">Pets Included</span></div><small class="mut">${state.encounterId==='all'?'All encounters':'Focused encounter #'+state.encounterId}</small></div><div><span class="badge">${fmt(m.total)} damage</span><span class="badge">${fmt(m.combatDps)} combat DPS</span><span class="badge red">${num(deathRows(scopeRows(),p.id).length)} deaths</span></div></div>`}
function renderPlayers(){const sel=$('#player');sel.innerHTML=state.players.map(p=>`<option value="${esc(p.id)}" ${p.id===state.playerId?'selected':''}>${esc(p.name)}</option>`).join('');if(!state.players.length){$('#party').innerHTML='';return}const rows=state.players.map((p,i)=>{const m=NWParser.metrics(state.rows,p.id,state.encounters);return{rank:i+1,name:p.name,cls:inferClass(p.id),damage:m.total,dps:m.dps,combat:m.combatDps,hits:m.hits,duration:dur(m.duration)}});$('#party').innerHTML=`<section class="panel"><h3>Party Overview</h3>${table(rows,[['rank','#'],['name','Player'],['cls','Class'],['damage','Damage'],['dps','DPS'],['combat','Combat DPS'],['hits','Hits'],['duration','Duration']])}</section>`}
function renderChips(){if(!state.encounters.length){$('#chips').innerHTML='';return}const visible=state.showHidden?state.encounters:state.encounters.filter(e=>e.visible);const hidden=state.encounters.length-state.encounters.filter(e=>e.visible).length;$('#chips').innerHTML=`<button class="chip ${state.encounterId==='all'?'active':''}" data-e="all">All Encounters</button>`+visible.map(e=>`<button class="chip ${e.type} ${String(e.id)===String(state.encounterId)?'active':''}" data-e="${e.id}">${e.type==='boss'?'Boss':'Mob'} #${e.id} ${esc(e.label)} <span class="mut">${dur(e.duration)}</span></button>`).join('')+(hidden?`<button id="hidden" class="chip ghost">${state.showHidden?'Hide':'Show'} ${hidden} non-boss</button>`:'');$$('[data-e]').forEach(b=>b.onclick=()=>{state.encounterId=b.dataset.e;state.rawPower=null;render()});const h=$('#hidden');if(h)h.onclick=()=>{state.showHidden=!state.showHidden;render()}}
function bars(title,items,key='power',alt=''){const mx=Math.max(1,...items.map(x=>x.damage));return`<h3>${esc(title)}</h3><div class="bars">${items.map(x=>`<div class="barrow"><span>${esc(x[key])}</span><div class="bar ${alt}"><i style="width:${Math.max(2,x.damage/mx*100)}%"></i></div><b>${pct(x.share)}</b><em>${fmt(x.damage)}</em></div>`).join('')}</div>`}
function categoryRows(powers,total){return Array.from(group(powers,p=>p.category)).map(([category,rs])=>{const damage=sum(rs,r=>r.damage);return{category,damage,share:total?damage/total*100:0}}).sort((a,b)=>b.damage-a.damage)}
function renderOverview(rows,pid,encs){const m=NWParser.metrics(rows,pid,encs);const h=healingBreakdown(rows,pid);const ps=NWParser.powers(rows,pid);const cats=categoryRows(ps,m.total);const max=m.max;$('#content').innerHTML=playerHeader()+`<section class="panel"><h3>Overview</h3><div class="cards">${card('Total Damage',fmt(m.total))}${card('DPS',fmt(m.dps))}${card('Combat DPS',fmt(m.combatDps))}${card('Duration',dur(m.duration))}${card('In-Combat Time',dur(m.combatTime))}${card('Total Hits',num(m.hits))}${card('Crit Rate',pct(m.crit))}${card('Flank Rate',pct(m.flank))}${card('Max Hit '+(max?'('+esc(max.powerName)+')':''),fmt(max?.amount||0))}${card('Encounters',encs.length)}${card('Healing Done',fmt(h.done.total))}${card('Damage Taken',fmt(damageTaken(rows,pid).total))}${card('Shielded',fmt(shielding(rows,pid).total))}</div><div class="grid2"><div>${bars('Top Damage Powers',ps.slice(0,8))}</div><div>${bars('Damage by Category',cats,'category','orange')}</div></div></section>`}
function renderDamage(rows,pid){const ps=NWParser.powers(rows,pid);let html=`<section class="panel"><h3>Damage Out - ${ps.length} Powers</h3><div class="table"><table><thead><tr><th>Power</th><th>Category</th><th>Hits</th><th>Damage</th><th>%</th><th>Avg</th><th>Max</th><th>Crit%</th></tr></thead><tbody>`;html+=ps.map((p,i)=>`<tr class="powerRow" data-power="${i}"><td>› <b>${esc(p.power)}</b></td><td>${esc(p.category)}</td><td>${num(p.hits)}</td><td>${fmt(p.damage)}</td><td>${pct(p.share)}</td><td>${fmt(p.avg)}</td><td>${fmt(p.max)}</td><td>${pct(p.crit)}</td></tr>`).join('');html+=`</tbody></table></div><div id="raw"></div></section>`;$('#content').innerHTML=playerHeader()+html;$$('[data-power]').forEach(tr=>tr.onclick=()=>renderRaw(ps[+tr.dataset.power]));if(state.rawPower){const p=ps.find(x=>x.power===state.rawPower);if(p)renderRaw(p)}}
function flagBadges(r){const b=[];if(r.flags.has('Critical'))b.push(['CRIT','crit']);if(r.flags.has('Flank'))b.push(['CA','ca']);if(r.flags.has('Dodge'))b.push(['DEFLECT','deflect']);if(r.flags.has('Kill'))b.push(['KILL','kill']);return b.map(x=>`<span class="flag ${x[1]}">${x[0]}</span>`).join(' ')}
function renderRaw(power){state.rawPower=power.power;const first=power.rows[0]?.time||0;const rows=power.rows.map(r=>({timeRaw:r.timestampRaw,offset:'+'+(r.time-first).toFixed(2)+'s',target:r.targetName,damage:r.amount,base:r.baseAmount,debuff:r.baseAmount?((r.amount/r.baseAmount-1)*100).toFixed(0)+'%':'-',type:r.damageType,flags:flagBadges(r)}));$('#raw').innerHTML=`<div class="raw"><h3>Raw hits - ${esc(power.power)} (${power.rows.length})</h3><div class="table"><table><thead><tr><th>Time</th><th>Offset</th><th>Target</th><th>Damage</th><th>Base</th><th>Debuff%</th><th>Type</th><th>Flags</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.timeRaw)}</td><td>${esc(r.offset)}</td><td>${esc(r.target)}</td><td>${fmt(r.damage)}</td><td>${fmt(r.base)}</td><td>${esc(r.debuff)}</td><td>${esc(r.type)}</td><td>${r.flags}</td></tr>`).join('')}</tbody></table></div></div>`}
function healingBreakdown(rows,pid){const out=rows.filter(r=>r.ownerId===pid&&r.damageType==='HitPoints'&&r.amount<0);const inc=rows.filter(r=>r.targetId===pid&&r.damageType==='HitPoints'&&r.amount<0);function mk(list){const total=sum(list,r=>Math.abs(r.amount));return{total,rows:Array.from(group(list,r=>r.powerName)).map(([power,rs])=>{const v=sum(rs,r=>Math.abs(r.amount));return{power,ticks:rs.length,total:v,share:total?v/total*100:0,avg:v/rs.length,max:Math.max(...rs.map(r=>Math.abs(r.amount))),critRate:rs.filter(r=>r.flags.has('Critical')).length/rs.length*100}}).sort((a,b)=>b.total-a.total)}}return{done:mk(out),received:mk(inc)}}
function renderHealing(rows,pid){const h=healingBreakdown(rows,pid);const m=NWParser.metrics(rows,pid,activeEncounters());$('#content').innerHTML=playerHeader()+`<section class="panel"><h3>Healing - ${fmt(h.done.total)} Done - ${fmt(h.done.total/Math.max(1,m.duration))} HPS</h3><h3>Healing Done</h3>${table(h.done.rows,[['power','Power'],['ticks','Ticks'],['total','Total'],['share','%'],['avg','Avg'],['max','Max'],['critRate','Crit%']])}<h3>Healing Received</h3>${table(h.received.rows,[['power','Power'],['ticks','Ticks'],['total','Total'],['avg','Avg'],['max','Max']])}</section>`}
function damageTaken(rows,pid){const list=rows.filter(r=>r.targetId===pid&&r.damageType==='Physical'&&r.amount>0);const total=sum(list,r=>r.amount);const bySource=Array.from(group(list,r=>(r.ownerName||'-')+'|'+r.powerName)).map(([k,rs])=>{const [source,power]=k.split('|');const damage=sum(rs,r=>r.amount);return{source,power,hits:rs.length,damage,share:total?damage/total*100:0,max:Math.max(...rs.map(r=>r.amount))}}).sort((a,b)=>b.damage-a.damage);const byType=Array.from(group(list,r=>r.powerName)).map(([power,rs])=>{const damage=sum(rs,r=>r.amount);return{power,hits:rs.length,damage,share:total?damage/total*100:0,max:Math.max(...rs.map(r=>r.amount))}}).sort((a,b)=>b.damage-a.damage);return{total,bySource,byType}}
function renderTaken(rows,pid){const x=damageTaken(rows,pid);$('#content').innerHTML=playerHeader()+`<section class="panel"><h3>Damage Taken - ${fmt(x.total)} Total</h3><h3>By Source</h3>${table(x.bySource,[['source','Source'],['power','Power'],['hits','Hits'],['damage','Damage'],['share','%'],['max','Max']])}<h3>By Type</h3>${table(x.byType,[['power','Power'],['hits','Hits'],['damage','Damage'],['share','%'],['max','Max']])}</section>`}
function shielding(rows,pid){const list=rows.filter(r=>r.targetId===pid&&r.damageType==='Shield'&&r.amount<0);const total=sum(list,r=>Math.abs(r.amount));const by=Array.from(group(list,r=>(r.ownerName||'-')+'|'+r.powerName)).map(([k,rs])=>{const [source,power]=k.split('|');const absorbed=sum(rs,r=>Math.abs(r.amount));const base=sum(rs,r=>Math.abs(r.baseAmount||r.amount));return{source,power,hits:rs.length,absorbed,share:total?absorbed/total*100:0,full:rs.filter(r=>!r.flags.has('ShieldBreak')).length,breaks:rs.filter(r=>r.flags.has('ShieldBreak')).length,effect:base?absorbed/base*100:0}}).sort((a,b)=>b.absorbed-a.absorbed);return{total,rows:by}}
function renderShield(rows,pid){const x=shielding(rows,pid);$('#content').innerHTML=playerHeader()+`<section class="panel"><h3>Shielding - ${fmt(x.total)} Absorbed</h3>${table(x.rows,[['source','Source'],['power','Power'],['hits','Hits'],['absorbed','Absorbed'],['share','%'],['full','Full Absorbs'],['breaks','Breaks'],['effect','Effectiveness']])}</section>`}
function positioning(rows,pid){const eligible=NWParser.validForPlayer(rows,pid).filter(r=>!r.flags.has('Dodge'));const actual=sum(eligible,r=>r.amount);const ca=eligible.filter(r=>r.flags.has('Flank'));const non=sum(eligible.filter(r=>!r.flags.has('Flank')),r=>r.amount);const missed=non*(state.ca-1);const potential=actual+missed;const tableRows=Array.from(group(eligible,r=>r.powerName)).map(([power,rs])=>{const damage=sum(rs,r=>r.amount);const caHits=rs.filter(r=>r.flags.has('Flank')).length;const nonca=sum(rs.filter(r=>!r.flags.has('Flank')),r=>r.amount);return{power,category:NWParser.category(power),hits:rs.length,caHits,caRate:rs.length?caHits/rs.length*100:0,damage,nonca,missed:nonca*(state.ca-1)}}).sort((a,b)=>b.missed-a.missed);return{actual,hits:eligible.length,caHits:ca.length,uptime:eligible.length?ca.length/eligible.length*100:0,missed,potential,eff:potential?actual/potential*100:100,rows:tableRows}}
function renderPosition(rows,pid){const x=positioning(rows,pid);$('#content').innerHTML=playerHeader()+`<section class="panel"><h3>Combat Advantage - Positioning Analysis</h3><div class="filterbar"><label>CA Multiplier <input id="caInput" type="number" step="0.1" value="${state.ca}"></label></div><div class="cards">${card('CA Uptime (hits)',pct(x.uptime))}${card('Positioning Efficiency',pct(x.eff))}${card('Actual Damage',fmt(x.actual))}${card('Potential Damage',fmt(x.potential))}${card('Missed CA Damage',fmt(x.missed))}</div>${table(x.rows,[['power','Power'],['category','Category'],['hits','Hits'],['caHits','CA Hits'],['caRate','CA %'],['damage','Damage'],['nonca','Non-CA Dmg'],['missed','Missed']])}</section>`;$('#caInput').onchange=e=>{state.ca=+e.target.value||2.2;render()}}
function timing(rows,pid){const all=NWParser.validForPlayer(rows,pid).filter(r=>r.baseAmount>0);const byTarget=group(all,r=>r.targetId);const eligible=all.filter(r=>{const c=NWParser.category(r.powerName);return c==='Daily'||c==='Mount'||(state.includeEnc&&c==='Encounter')});const out=eligible.map(r=>{const cur=r.amount/r.baseAmount;let best=cur,bt=r.time;for(const x of byTarget.get(r.targetId)||[]){const mult=x.amount/x.baseAmount;if(Math.abs(x.time-r.time)<=15&&mult>best){best=mult;bt=x.time}}const potential=best>cur?r.amount/cur*best:r.amount;return{power:r.powerName+(r.flags.has('Critical')?' CRIT':''),category:NWParser.category(r.powerName),time:r.time,mult:cur,best,offset:bt-r.time,damage:r.amount,potential,missed:Math.max(0,potential-r.amount)}}).sort((a,b)=>b.missed-a.missed);const actual=sum(out,r=>r.damage),potential=sum(out,r=>r.potential);return{actual,potential,missed:potential-actual,eff:potential?actual/potential*100:100,rows:out}}
function renderTiming(rows,pid){const x=timing(rows,pid);$('#content').innerHTML=playerHeader()+`<section class="panel"><h3>Activation Timing Analysis</h3><p class="mut">Compares each activation multiplier to the best same-target debuff window within +/-15 seconds. Party-wide buffs are not inferred from the raw log.</p><div class="filterbar"><label><input id="incEnc" type="checkbox" ${state.includeEnc?'checked':''}> Include Encounter powers</label></div><div class="cards">${card('Timing Efficiency',pct(x.eff))}${card('Actual Damage',fmt(x.actual))}${card('Potential Damage',fmt(x.potential))}${card('Missed Damage',fmt(x.missed))}</div>${table(x.rows.slice(0,250),[['power','Power'],['category','Category'],['time','Time'],['mult','Mult'],['best','Best'],['offset','Offset'],['damage','Damage'],['potential','Potential'],['missed','Missed']])}</section>`;$('#incEnc').onchange=e=>{state.includeEnc=e.target.checked;render()}}
function timelineData(rows,pid){const d=NWParser.validForPlayer(rows,pid).sort((a,b)=>a.time-b.time);if(!d.length)return[];const out=[];let left=0,right=0,damage=0;for(let t=Math.floor(d[0].time);t<=Math.ceil(d[d.length-1].time);t++){while(right<d.length&&d[right].time<=t){damage+=d[right].amount;right++}while(left<right&&d[left].time<=t-3){damage-=d[left].amount;left++}out.push({time:t,dps:damage/3})}return out}
function chartSvg(data){if(!data.length)return'<div class="empty">No DPS data</div>';const w=1200,h=260,p=28,max=Math.max(...data.map(d=>d.dps),1);const pts=data.map((d,i)=>`${p+i/(data.length-1)*(w-p*2)},${h-p-d.dps/max*(h-p*2)}`).join(' ');return`<svg class="chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline fill="none" stroke="#8796ff" stroke-width="2" points="${pts}"></polyline><text x="${p}" y="22" fill="#aab3c5">Peak 3s DPS: ${fmt(max)}</text></svg>`}
function renderTimeline(rows,pid){const ps=NWParser.powers(rows,pid);let filtered=ps;if(state.filter==='class')filtered=ps.filter(p=>['At-Will','Encounter','Daily','Feat','Class Feature'].includes(p.category));if(state.filter==='proc')filtered=ps.filter(p=>['Item / Enchant','Mount','Other / Unknown'].includes(p.category));if(state.filter==='pets')filtered=ps.filter(p=>p.category==='Pet / Companion');const top=filtered.slice(0,16);const all=NWParser.validForPlayer(rows,pid);const start=all[0]?.time||0,end=all[all.length-1]?.time||start+1,span=Math.max(1,end-start);const activations=top.map(p=>`<div class="actRow"><b>${esc(p.power)}</b><div class="actTrack">${p.rows.map(r=>`<i class="tick ${r.flags.has('Critical')?'crit':''}" style="left:${((r.time-start)/span*100).toFixed(2)}%"></i>`).join('')}</div></div>`).join('');const freq=top.map(p=>{const first=p.rows[0]?.time||0,last=p.rows[p.rows.length-1]?.time||0;return{power:p.power,category:p.category,hits:p.hits,first:first-start,last:last-start,avg:p.hits>1?(last-first)/(p.hits-1):0}});const cdRows=top.filter(p=>CD[p.power]).map(p=>{const cd=CD[p.power],uses=p.hits,max=Math.floor((end-start)/cd)+1;return{power:p.power,category:p.category,cd:cd+'s',hits:uses,max,eff:max?uses/max*100:0}});$('#content').innerHTML=playerHeader()+`<section class="panel"><h3>Timeline & Powers</h3><div class="timelineBox"><h3>DPS (3s rolling)</h3>${chartSvg(timelineData(rows,pid))}</div><div class="filterbar"><button class="${state.filter==='all'?'active':''}" data-filter="all">All</button><button class="${state.filter==='class'?'active':''}" data-filter="class">Class Powers</button><button class="${state.filter==='proc'?'active':''}" data-filter="proc">Procs & Items</button><button class="${state.filter==='pets'?'active':''}" data-filter="pets">Pets</button></div><div class="timelineBox"><h3>Power Activations</h3><div class="activationRows">${activations||'<div class="empty">No activations</div>'}</div></div><h3>Power Usage Frequency</h3>${table(freq,[['power','Power'],['category','Category'],['hits','Activations'],['first','First Use'],['last','Last Use'],['avg','Avg Interval']])}<h3>Cooldown Efficiency</h3>${table(cdRows,[['power','Power'],['category','Type'],['cd','CD'],['hits','Uses'],['max','Max'],['eff','Efficiency']])}</section>`;$$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()})}
function deathRows(rows,pid){return rows.filter(r=>r.targetId===pid&&r.damageType==='Physical'&&r.amount>0&&r.flags.has('Kill')).sort((a,b)=>a.time-b.time)}
function renderDeaths(rows,pid){const deaths=deathRows(rows,pid);$('#content').innerHTML=playerHeader()+`<section class="panel"><h3>Deaths - ${deaths.length} Total</h3><div class="timelineBox"><h3>Incoming Damage Timeline</h3>${chartSvg(incomingDps(rows,pid))}</div><h3>Death Log</h3>${deaths.map(d=>`<div class="deathCard"><small>${esc(d.timestampRaw)}</small><br>Killed by <b>${esc(d.ownerName)}</b> with <b>${esc(d.powerName)}</b><br><span class="badge red">${fmt(d.amount)} ${esc(d.damageType)}</span> ${d.flags.has('Critical')?'<span class="flag crit">CRIT</span>':''}</div>`).join('')||'<div class="empty">No deaths</div>'}</section>`}
function incomingDps(rows,pid){const d=rows.filter(r=>r.targetId===pid&&r.damageType==='Physical'&&r.amount>0).sort((a,b)=>a.time-b.time);if(!d.length)return[];const out=[];let left=0,right=0,damage=0;for(let t=Math.floor(d[0].time);t<=Math.ceil(d[d.length-1].time);t++){while(right<d.length&&d[right].time<=t){damage+=d[right].amount;right++}while(left<right&&d[left].time<=t-3){damage-=d[left].amount;left++}out.push({time:t,dps:damage/3})}return out}
function renderOther(rows,pid){const outgoing=rows.filter(r=>r.ownerId===pid);const types=Array.from(group(outgoing,r=>r.damageType||'Unknown')).map(([type,rs])=>({type,hits:rs.length,damage:sum(rs,r=>Math.abs(r.amount))})).sort((a,b)=>b.damage-a.damage);const flags=Array.from(group(outgoing.flatMap(r=>(r.flagsRaw||'').split('|').filter(Boolean)),x=>x)).map(([flag,rs])=>({flag,hits:rs.length})).sort((a,b)=>b.hits-a.hits);const unknown=NWParser.powers(rows,pid).filter(p=>p.category==='Other / Unknown');$('#content').innerHTML=playerHeader()+`<section class="panel"><h3>Other</h3><h3>Damage / Event Types</h3>${table(types,[['type','Type'],['hits','Rows'],['damage','Magnitude']])}<h3>Flags</h3>${table(flags,[['flag','Flag'],['hits','Count']])}<h3>Other / Unknown Powers</h3>${table(unknown,[['power','Power'],['hits','Hits'],['damage','Damage'],['share','%'],['avg','Avg'],['max','Max']])}</section>`}
function renderFormulas(){$('#content').innerHTML=`<section class="panel"><h3>Combat Formulas</h3>${['Valid damage = selected player + Physical + amount > 0 + not ShowPowerDisplayName','Total Damage = sum(final logged damage amount)','DPS = Total Damage / first-to-last valid damage duration','Combat DPS = Total Damage / active encounter time','Crit Rate = critical hit count / total hit count','Flank Rate = flank hit count / total hit count','Debuff% in raw hits = (Damage / Base - 1) x 100','CA missed damage = non-CA damage x (CA multiplier - 1)','Timing potential = damage / current multiplier x best multiplier within +/-15s','Boss = entity template contains _Boss','Mob = entity template contains _Solo, _Elite, _Standard, or _Minion','Rating contribution = 50 + (Rating - TIL) / 1000','Base Damage = (TIL / 10) x role multiplier','Theoretical damage = (Magnitude / 100) x Base Damage x Multipliers'].map(x=>`<div class="formula"><code>${esc(x)}</code></div>`).join('')}</section>`}
function render(){renderPlayers();renderChips();$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));if(!state.playerId){$('#content').innerHTML='<section class="panel"><div class="empty">Upload a combat log</div></section>';return}const rows=scopeRows(),pid=state.playerId,encs=activeEncounters();if(state.tab==='overview')renderOverview(rows,pid,encs);else if(state.tab==='timeline')renderTimeline(rows,pid);else if(state.tab==='damage')renderDamage(rows,pid);else if(state.tab==='healing')renderHealing(rows,pid);else if(state.tab==='taken')renderTaken(rows,pid);else if(state.tab==='shield')renderShield(rows,pid);else if(state.tab==='pos')renderPosition(rows,pid);else if(state.tab==='timing')renderTiming(rows,pid);else if(state.tab==='deaths')renderDeaths(rows,pid);else if(state.tab==='other')renderOther(rows,pid);else renderFormulas()}
async function load(file){$('#status').textContent='Reading '+file.name+'...';state.rows=NWParser.parseLog(await file.text());state.players=NWParser.detectPlayers(state.rows);state.playerId=state.players[0]?.id||'';state.encounterId='all';state.rawPower=null;rebuildEncounters();$('#status').textContent='Parsed '+state.rows.length.toLocaleString()+' rows.';render()}
$('#file').onchange=e=>{if(e.target.files[0])load(e.target.files[0])};$('#player').onchange=e=>{state.playerId=e.target.value;state.encounterId='all';state.rawPower=null;rebuildEncounters();render()};$('#mode').onchange=e=>{state.split=e.target.value;state.encounterId='all';rebuildEncounters();render()};$('#tabs').onclick=e=>{const b=e.target.closest('button');if(b&&b.dataset.tab){state.tab=b.dataset.tab;state.rawPower=null;render()}};render();
