const CAT={"Chilling Cloud":"At-Will","Magic Missile":"At-Will","Electric Shot":"At-Will","Rapid Shot":"At-Will","Icy Rays":"Encounter","Chill Strike":"Encounter","Repel":"Encounter","Entangling Force":"Encounter","Fanning the Flame":"Encounter","Fanned Flame":"Encounter","Gathering Flame":"Encounter","Fireball":"Encounter","Icy Terrain":"Encounter","Thorn Ward":"Encounter","Thorn Strike":"Encounter","Hindering Strike":"Encounter","Split the Sky":"Encounter","Throw Caution":"Encounter","Hindering Shot":"Encounter","Ice Knife":"Daily","Furious Immolation":"Daily","Forest Ghost":"Daily","Infernal Pounce":"Mount","Rimefire Smolder":"Feat","Shatter Strike":"Feat","Glowing Flames":"Feat","Grasping Roots":"Feat","Smolder":"Class Feature","Mark of the Giant Slayer, Rank 2":"Item / Enchant","Empowered Owlbear Figurine":"Item / Enchant","Spined Devil's Influence":"Item / Enchant","Lightning Flash":"Item / Enchant","Enchanter's Hex":"Item / Enchant","Loose the Ballista!":"Pet / Companion","Suppressing Fire!":"Pet / Companion","Slash":"Pet / Companion","Thrust":"Pet / Companion","Instructional Aid":"Pet / Companion","Life Lessons":"Other / Unknown","Radiant Weapon":"Other / Unknown","Blood Lust":"Other / Unknown","Tentacle Slam":"Other / Unknown","Infection":"Other / Unknown"};
const wait=()=>new Promise(r=>setTimeout(r,0));
function csv(line){const out=[];let c='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===','&&!q){out.push(c);c=''}else c+=ch}out.push(c);return out}
function sec(raw){const p=String(raw||'').split(':');if(p.length>=6)return(+p[2]||0)*86400+(+p[3]||0)*3600+(+p[4]||0)*60+(+p[5]||0);const d=Date.parse(raw);return Number.isFinite(d)?d/1000:0}
function parseEntity(id=''){const m=String(id).match(/^C\[(\d+)\s+(.+)\]$/);return m?{num:m[1],tpl:m[2],raw:id}:null}
function isPlayer(id){return String(id||'').startsWith('P[')}
function isCreature(id){return String(id||'').startsWith('C[')}
function isBoss(id){return (parseEntity(id)?.tpl||'').includes('_Boss')}
function isMob(id){const t=parseEntity(id)?.tpl||'';return !t.includes('_Boss')&&['_Solo','_Elite','_Standard','_Minion'].some(x=>t.includes(x))}
function isPet(id){const t=parseEntity(id)?.tpl||'';return /Pet_|Companion|Appointment/i.test(t)}
function isDamage(r){return r.damageType==='Physical'&&r.amount>0&&!r.flags.has('ShowPowerDisplayName')&&(r.targetId!=='*'||isCreature(r.sourceId))}
function normalizeColumns(cols){let c=cols.map(x=>String(x??'').trim());if(c[0]&&/^\d+$/.test(c[0])&&c[1]?.includes('::'))c=c.slice(1);if(c[0]?.toLowerCase()==='index'||c[0]?.toLowerCase().includes('timestamp'))return null;return c}
function parseLine(rawLine,lineNo){const line=String(rawLine||'').trim();if(!line||line.startsWith('index,'))return null;const c=normalizeColumns(csv(line));if(!c||c.length<12)return null;const k=c[0].indexOf('::');if(k<0)return null;const amount=Number(c[10]);if(!Number.isFinite(amount))return null;const ts=c[0].slice(0,k);return{lineNo,timestampRaw:ts,abs:sec(ts),time:0,ownerName:c[0].slice(k+2),ownerId:c[1]||'',sourceName:c[2]||'',sourceId:c[3]||'',targetName:c[4]||'',targetId:c[5]||'',powerName:c[6]||'Unknown',powerId:c[7]||'',damageType:c[8]||'',flags:new Set((c[9]||'').split('|').filter(Boolean)),flagsRaw:c[9]||'',amount,baseAmount:Number(c[11])||0}}
function finalizeRows(rows,meta){let first=Infinity;for(const r of rows)if(r.abs<first)first=r.abs;if(!Number.isFinite(first))first=0;for(const r of rows)r.time=Math.round((r.abs-first)*1000)/1000;rows.sort((a,b)=>a.time-b.time||a.lineNo-b.lineNo);rows.meta=meta||{};return rows}
function parseLog(text,opt={}){const rows=[];let skipped=0,lineNo=0;for(const line of String(text||'').split(/\r?\n/)){lineNo++;const r=parseLine(line,lineNo);if(r)rows.push(r);else if(line.trim())skipped++}return finalizeRows(rows,{skipped,lines:lineNo,bytes:String(text||'').length,mode:'text'})}
async function parseFile(file,opt={}){const rows=[];let skipped=0,lineNo=0,doneBytes=0,carry='';const onProgress=typeof opt.onProgress==='function'?opt.onProgress:null;const decoder=new TextDecoder();if(file.stream){const reader=file.stream().getReader();while(true){const res=await reader.read();if(res.done)break;doneBytes+=res.value.byteLength;const chunk=carry+decoder.decode(res.value,{stream:true});const parts=chunk.split(/\r?\n/);carry=parts.pop()||'';for(const line of parts){lineNo++;const r=parseLine(line,lineNo);if(r)rows.push(r);else if(line.trim())skipped++;if(lineNo%12000===0){onProgress&&onProgress({phase:'parsing',rows:rows.length,lines:lineNo,bytes:doneBytes,total:file.size||0});await wait()}}onProgress&&onProgress({phase:'reading',rows:rows.length,lines:lineNo,bytes:doneBytes,total:file.size||0})}const tail=carry+decoder.decode();if(tail.trim()){lineNo++;const r=parseLine(tail,lineNo);if(r)rows.push(r);else skipped++}}else{return parseLog(await file.text(),opt)}onProgress&&onProgress({phase:'finalizing',rows:rows.length,lines:lineNo,bytes:doneBytes,total:file.size||0});await wait();return finalizeRows(rows,{skipped,lines:lineNo,bytes:doneBytes,totalBytes:file.size||0,mode:'stream'})}
function detectPlayers(rows){const m=new Map();for(const r of rows){if(isPlayer(r.ownerId)){if(!m.has(r.ownerId))m.set(r.ownerId,{id:r.ownerId,name:r.ownerName,damage:0,hits:0});if(isDamage(r)){const p=m.get(r.ownerId);p.damage+=r.amount;p.hits++}}if(isPlayer(r.targetId)&&!m.has(r.targetId))m.set(r.targetId,{id:r.targetId,name:r.targetName,damage:0,hits:0})}return Array.from(m.values()).sort((a,b)=>b.damage-a.damage)}
function validForPlayer(rows,pid){const out=[];for(const r of rows)if(r.ownerId===pid&&isDamage(r))out.push(r);out.sort((a,b)=>a.time-b.time||a.lineNo-b.lineNo);return out}
function enemyStats(rows){const m=new Map();function add(id,name,damage,time){if(!isCreature(id)||isPet(id))return;if(!m.has(id)){const e=parseEntity(id);m.set(id,{id,name:name||e?.tpl||id,tpl:e?.tpl||'',damage:0,hits:0,boss:isBoss(id),mob:isMob(id),first:time})}const x=m.get(id);x.damage+=Math.max(0,damage||0);if((damage||0)>0)x.hits++;if(time<x.first)x.first=time}for(const r of rows){add(r.targetId,r.targetName,r.amount,r.time);if(r.sourceId&&r.sourceId!=='*'&&!isPlayer(r.sourceId))add(r.sourceId,r.sourceName,0,r.time)}return Array.from(m.values()).sort((a,b)=>a.boss!==b.boss?+b.boss-+a.boss:b.damage-a.damage||a.first-b.first)}
function makeEncounter(rs){rs=[...rs].sort((a,b)=>a.time-b.time||a.lineNo-b.lineNo);const es=enemyStats(rs);const type=es.some(e=>e.boss)?'boss':'mob';let names=es.slice(0,3).map(e=>e.name);let label=names.join(', ')||'Trash';if(es.length>3)label+=' +'+(es.length-3);if(type!=='boss'&&es.length<=4)label='Trash ('+es.length+' mobs)';return{rows:rs,start:rs[0].time,end:rs[rs.length-1].time,duration:rs[rs.length-1].time-rs[0].time,type,label,visible:type==='boss',bossIds:new Set(es.filter(e=>e.boss).map(e=>e.id)),enemyStats:es}}
function sameBoss(a,b){for(const id of a.bossIds)if(b.bossIds.has(id))return true;return false}
function mergeEnc(list){return makeEncounter(list.flatMap(e=>e.rows))}
function buildEncounters(rows,pid,mode='player'){const src=(mode==='party'?rows.filter(r=>isPlayer(r.ownerId)&&isDamage(r)):validForPlayer(rows,pid)).sort((a,b)=>a.time-b.time||a.lineNo-b.lineNo);if(!src.length)return[];const raw=[];let cur=[];for(const r of src){if(cur.length&&r.time-cur[cur.length-1].time>5){raw.push(makeEncounter(cur));cur=[]}cur.push(r)}if(cur.length)raw.push(makeEncounter(cur));const out=[];for(let i=0;i<raw.length;i++){const e=raw[i],n=raw[i+1],a=raw[i+2];if(e.type==='boss'&&n&&a&&a.type==='boss'&&sameBoss(e,a)&&n.start-e.end<=15&&a.start-n.end<=15){out.push(mergeEnc([e,n,a]));i+=2;continue}const p=out[out.length-1];if(p&&p.type==='boss'&&e.type==='boss'&&sameBoss(p,e)&&e.start-p.end<=15)out[out.length-1]=mergeEnc([p,e]);else out.push(e)}return out.map((e,i)=>({...e,id:i+1}))}
function category(power){return CAT[power]||'Other / Unknown'}
function group(rows,fn){const m=new Map();for(const r of rows){const k=fn(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return m}
function metrics(rows,pid,encounters=[]){const d=validForPlayer(rows,pid);let total=0,crit=0,flank=0,max=null;for(const r of d){total+=r.amount;if(r.flags.has('Critical'))crit++;if(r.flags.has('Flank'))flank++;if(!max||r.amount>max.amount)max=r}const hits=d.length,first=hits?d[0].time:0,last=hits?d[hits-1].time:0;let combat=0;for(const e of encounters){let f=null,l=null;for(const r of d){if(r.time<e.start)continue;if(r.time>e.end)break;if(f===null)f=r.time;l=r.time}if(f!==null&&l!==null)combat+=l-f}return{total,hits,duration:last-first,dps:total/Math.max(1,last-first),combatTime:combat,combatDps:total/Math.max(1,combat),crit:hits?crit/hits*100:0,flank:hits?flank/hits*100:0,max}}
function powers(rows,pid){const d=validForPlayer(rows,pid);let total=0;for(const r of d)total+=r.amount;const out=[];for(const [power,rs] of group(d,r=>r.powerName)){let damage=0,max=0,crit=0;for(const r of rs){damage+=r.amount;if(r.amount>max)max=r.amount;if(r.flags.has('Critical'))crit++}out.push({power,category:category(power),hits:rs.length,damage,share:total?damage/total*100:0,avg:rs.length?damage/rs.length:0,max,crit:rs.length?crit/rs.length*100:0,rows:rs.sort((a,b)=>a.time-b.time||a.lineNo-b.lineNo)})}return out.sort((a,b)=>b.damage-a.damage)}
function healing(rows,pid){let done=0,received=0;for(const r of rows){if(r.damageType==='HitPoints'&&r.amount<0){if(r.ownerId===pid)done+=Math.abs(r.amount);if(r.targetId===pid)received+=Math.abs(r.amount)}}return{done,received}}
function taken(rows,pid){let v=0;for(const r of rows)if(r.targetId===pid&&r.damageType==='Physical'&&r.amount>0)v+=r.amount;return v}
function shielded(rows,pid){let v=0;for(const r of rows)if(r.targetId===pid&&r.damageType==='Shield'&&r.amount<0)v+=Math.abs(r.amount);return v}
function createEngine(rows){return{rows,players:()=>detectPlayers(rows),encounters:(pid,mode)=>buildEncounters(rows,pid,mode),metrics:(pid,scope=rows,enc=[])=>metrics(scope,pid,enc),powers:(pid,scope=rows)=>powers(scope,pid),valid:(pid,scope=rows)=>validForPlayer(scope,pid)}}
window.NWParser={parseLog,parseFile,parseLine,detectPlayers,buildEncounters,metrics,powers,healing,taken,shielded,isDamage,validForPlayer,category,createEngine,parseEntity,isBoss,isMob};
